### ISSUE TITLE
Failed to load fuse package

### ISSUE THREAD

**Issue by anettegj** [fusetools/Fuse.AtomPlugin#36]
* Installed Atom from the internet
![atom-error](https://user-images.githubusercontent.com/20278779/29067908-e9037aa4-7c34-11e7-9bd6-69bed716dd98.png)

Stacktrace
```
Failed to load the fuse package
Cannot find module 'atom-space-pen-views'
Hide Stack Trace
Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/private/var/folders/n6/95dkl7b5287dgl9scjnb7nw80000gn/T/AppTranslocation/BA663656-4C5E-4C12-92E1-F85DB2EA606C/d/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/private/var/folders/n6/95dkl7b5287dgl9scjnb7nw80000gn/T/AppTranslocation/BA663656-4C5E-4C12-92E1-F85DB2EA606C/d/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (file:///private/var/folders/n6/95dkl7b5287dgl9scjnb7nw80000gn/T/AppTranslocation/BA663656-4C5E-4C12-92E1-F85DB2EA606C/d/Atom.app/Contents/Resources/app/static/index.js:40:43)
    at require (/private/var/folders/n6/95dkl7b5287dgl9scjnb7nw80000gn/T/AppTranslocation/BA663656-4C5E-4C12-92E1-F85DB2EA606C/d/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/logan/.atom/packages/fuse/lib/errorListView.coffee:1:45)
    at Object.<anonymous> (/Users/logan/.atom/packages/fuse/lib/errorListView.coffee:1:1)
    at Module.get_Module._compile (/private/var/folders/n6/95dkl7b5287dgl9scjnb7nw80000gn/T/AppTranslocation/BA663656-4C5E-4C12-92E1-F85DB2EA606C/d/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/private/var/folders/n6/95dkl7b5287dgl9scjnb7nw80000gn/T/AppTranslocation/BA663656-4C5E-4C12-92E1-F85DB2EA606C/d/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (file:///private/var/folders/n6/95dkl7b5287dgl9scjnb7nw80000gn/T/AppTranslocation/BA663656-4C5E-4C12-92E1-F85DB2EA606C/d/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/private/var/folders/n6/95dkl7b5287dgl9scjnb7nw80000gn/T/AppTranslocation/BA663656-4C5E-4C12-92E1-F85DB2EA606C/d/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/logan/.atom/packages/fuse/lib/fuse.coffee:6:35)
    at Object.<anonymous> (/Users/logan/.atom/packages/fuse/lib/fuse.coffee:1:1)
    at Module.get_Module._compile (/private/var/folders/n6/95dkl7b5287dgl9scjnb7nw80000gn/T/AppTranslocation/BA663656-4C5E-4C12-92E1-F85DB2EA606C/d/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/private/var/folders/n6/95dkl7b5287dgl9scjnb7nw80000gn/T/AppTranslocation/BA663656-4C5E-4C12-92E1-F85DB2EA606C/d/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (file:///private/var/folders/n6/95dkl7b5287dgl9scjnb7nw80000gn/T/AppTranslocation/BA663656-4C5E-4C12-92E1-F85DB2EA606C/d/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/private/var/folders/n6/95dkl7b5287dgl9scjnb7nw80000gn/T/AppTranslocation/BA663656-4C5E-4C12-92E1-F85DB2EA606C/d/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/private/var/folders/n6/95dkl7b5287dgl9scjnb7nw80000gn/T/AppTranslocation/BA663656-4C5E-4C12-92E1-F85DB2EA606C/d/Atom.app/Contents/Resources/app/src/package.js:887:35)
    at /private/var/folders/n6/95dkl7b5287dgl9scjnb7nw80000gn/T/AppTranslocation/BA663656-4C5E-4C12-92E1-F85DB2EA606C/d/Atom.app/Contents/Resources/app/src/package.js:158:34
    at Package.module.exports.Package.measure (/private/var/folders/n6/95dkl7b5287dgl9scjnb7nw80000gn/T/AppTranslocation/BA663656-4C5E-4C12-92E1-F85DB2EA606C/d/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (/private/var/folders/n6/95dkl7b5287dgl9scjnb7nw80000gn/T/AppTranslocation/BA663656-4C5E-4C12-92E1-F85DB2EA606C/d/Atom.app/Contents/Resources/app/src/package.js:144:18)
    at PackageManager.module.exports.PackageManager.loadAvailablePackage (/private/var/folders/n6/95dkl7b5287dgl9scjnb7nw80000gn/T/AppTranslocation/BA663656-4C5E-4C12-92E1-F85DB2EA606C/d/Atom.app/Contents/Resources/app/src/package-manager.js:565:22)
    at /private/var/folders/n6/95dkl7b5287dgl9scjnb7nw80000gn/T/AppTranslocation/BA663656-4C5E-4C12-92E1-F85DB2EA606C/d/Atom.app/Contents/Resources/app/src/package-manager.js:479:25
    at Config.module.exports.Config.transact (/private/var/folders/n6/95dkl7b5287dgl9scjnb7nw80000gn/T/AppTranslocation/BA663656-4C5E-4C12-92E1-F85DB2EA606C/d/Atom.app/Contents/Resources/app/src/config.js:321:22)
    at PackageManager.module.exports.PackageManager.loadPackages (/private/var/folders/n6/95dkl7b5287dgl9scjnb7nw80000gn/T/AppTranslocation/BA663656-4C5E-4C12-92E1-F85DB2EA606C/d/Atom.app/Contents/Resources/app/src/package-manager.js:473:25)
    at /private/var/folders/n6/95dkl7b5287dgl9scjnb7nw80000gn/T/AppTranslocation/BA663656-4C5E-4C12-92E1-F85DB2EA606C/d/Atom.app/Contents/Resources/app/src/atom-environment.js:812:34

```
**When you dismiss the error message, ux-markup won’t be recognized**
This is what the fuse atom plugin looks like from the atom package view.  Note that the fuse icon does not appear:
![image](https://user-images.githubusercontent.com/20278779/29067971-1eaaef5c-7c35-11e7-9fa6-e8badaabccd2.png)

**Comment by guroen** [comment]
The user installed the plugin from this file: 

[Fuse.AtomPlugin-master.zip](https://github.com/fusetools/Fuse.AtomPlugin/files/1208468/Fuse.AtomPlugin-master.zip)

and this installation guide:
How to manually install Atom Plugin for Fuse

    • OS X: ~/.atom/packages/fuse
    • Windows: %userprofile%\.atom\packages\fuse
extract zip to Packages directory:

**Comment by BeeWarloc** [comment]
Judging from the output it seems like we need to also include the `atom-space-pen-views` package, as that's a dependency not installed in Atom by default. Or just add downloading and installing that package to the offline install guide.

**Comment by anettegj** [comment]
Hehe @BeeWarloc  I was just googling that error: 
https://discuss.atom.io/t/cannot-find-module-atom-space-pen-views/15691/6

**Comment by anettegj** [comment]
Dependencies to the atom plugin can be found here https://github.com/fusetools/Fuse.AtomPlugin/blob/master/package.json
