### ISSUE TITLE
"Could not be spawned" after installing package

### ISSUE THREAD

**Issue by fergatron** [fusetools/Fuse.AtomPlugin#38]
Hi, I installed fuse through the Atom app. After the install (or anytime I startup Atom) I get the following error:

![screenshot from 2017-10-26 11-05-00](https://user-images.githubusercontent.com/110601/32060839-f8ad35de-ba3d-11e7-8240-d4b4a7b72e49.png)

I then looked at Console and saw the following error:

> Uncaught Error: spawn fuse ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

OS: Fedora 26 (Linux 4.13.5-200.fc26.x86_64)
Atom 1.19.2 x64
Plugin: fuse 0.4.0

**Comment by knatten** [comment]
Hi, Fuse does not support Linux, and the Atom plugin needs to connect to Fuse for things like code completion, launching preview etc. Maybe [Fuse](https://www.fusetools.com/) isn't what you're looking for here?
